### ISSUE TITLE
Tiago deployment

### ISSUE THREAD

**Issue by bmegli** [Extend-Robotics/rosbridge_suite#2]
Runtime dependency problem with `builtins`

Identified [here](https://github.com/Extend-Robotics/extend_sensekit/issues/9#issuecomment-1069283522)

Temporary workaround there

**Comment by bmegli** [comment]
Another related link found yesterday by @Nitish
https://github.com/RobotWebTools/roslibjs/issues/390#issuecomment-744750796

**Comment by bmegli** [comment]
@nitish3693 

The supposed fix in 11.13 is here:
- https://github.com/RobotWebTools/rosbridge_suite/pull/542

We already have this version.

Looking more closely, the files changed:
- https://github.com/RobotWebTools/rosbridge_suite/pull/542/files

The fix works by marking python-future as dependency when using python2
```xml
<exec_depend condition="$ROS_PYTHON_VERSION == 2">python-future</exec_depend>
```

This doesn't solve the problem on Tiago for us.
It will not install the new dependency automatically.

I think there are two ways:
- upgrading the Tiago (maybe it upgrades melodic to latest and pulls dependencies)
- just installing the dependency (e.g. disabling read-only, installing by apt, re-enabling read only)
  - this is how we temporarily solved it in OU

Both ways would have to be agreed with OU.

**Comment by nitish3693** [comment]
Potential Fix Procedure options : 
* https://stackoverflow.com/questions/7143077/installing-pip-packages-to-home-folder
* the condition in `<build_depend condition="$ROS_PYTHON_VERSION == 2">python-future</build_depend>` might not be getting met on the developer machine making it not part of the install pushed to the Tiago. Lets  try by removing the condition

**Comment by bmegli** [comment]
For the first potential fix we mean:
- install pip in read only (to RAM), it will revert after reboot
- install python-future with pip for current user (into home), it will not revert after reboot

**Comment by Changliu52** [comment]
- We may need to add repository for tiago with source code with a .bash to automate the deployment.
- to share with Open University, we should share the binary and .bash to automate copying binaries to the right location in Tiago ( to be tested)

**Comment by bmegli** [comment]
@nitish3693 mentioned after OU tests 30.03.2021 that the following fix for rosbridge dependencies worked:

> - install pip in read only (to RAM), it will revert after reboot
> - install python-future with pip for current user (into home), it will not revert after reboot
